#!/bin/zsh

APP_DIR=`dirname "$0"`
APP_DIR=`cd "$APP_DIR";pwd`
export APP_DIR


cd $APP_DIR/frontend/src; flow

cd $APP_DIR
xterm -e "babel --modules common -w -d frontend/compiled frontend/src --ignore frontend/src/node_modules" &
sleep 2s; xterm -e "zsh -c \"while true; do browserify -o frontend/web/javascript/bundle.js frontend/compiled/live/helloworld.js; inotifywait -r frontend/compiled; done\"" &

