#!/bin/zsh

APP_DIR=`dirname "$0"`
APP_DIR=`cd "$APP_DIR";pwd`
export APP_DIR


cd $APP_DIR/frontend/src; flow

cd $APP_DIR
xterm -T babel -e "babel --modules common -w -d frontend/compiled frontend/src --ignore frontend/src/node_modules" &
sleep 2s;
xterm -T browserify -e "zsh -c \"while true; do browserify -o backend/sqlite/static/javascript/bundle.js frontend/compiled/live/app.js; inotifywait -r frontend/compiled; done\"" &
cd $APP_DIR/backend/sqlite
stack build && stack exec -- yesod devel
