Default: &defaults
  database: sqlite.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: sqlite_test.sqlite3
  <<: *defaults

Staging:
  database: sqlite_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: sqlite_production.sqlite3
  poolsize: 100
  <<: *defaults
