Default: &defaults
  database: sqlite2.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: sqlite2_test.sqlite3
  <<: *defaults

Staging:
  database: sqlite2_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: sqlite2_production.sqlite3
  poolsize: 100
  <<: *defaults
